version: 2.1
jobs: 
  pull-dlc:
    machine: true
    docker_layer_caching: true
    steps:
      - checkout
      - run: docker pull slightlytyler/large-image-test:latest

  pull-no-dlc:
    machine: true
    steps:
      - checkout
      - run: docker pull slightlytyler/large-image-test:latest
      
workflows:
  main:
    jobs:
      - pull-dlc
      - pull-no-dlc
