version: 2.1
jobs: 
  pull-dlc:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run: docker pull slightlytyler/large-image-test:latest

  docker-no-dlc:
    docker:
      - image: alpine:3
    resource_class: large
    steps:
      - checkout
      
workflows:
  main:
    jobs:
      - docker-no-dlc
