version: 2.1
executors:
  default:
    docker:
      - image: cimg/base:stable
jobs: 
  build:
    executor: default
    steps:
      - checkout
      - run: echo "hello"
workflows:
  main:
    jobs:
      - build
