version: 2.1
jobs: 
  pull-dlc:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run: docker pull slightlytyler/large-image-test:latest
      

  ubuntu-job:
    machine: true
    resource_class: medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"

  docker-no-dlc:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
workflows:
  main:
    jobs:
      - docker-no-dlc
      - ubuntu-job
