version: 2.1
executors:
  default:
    docker:
      - image: 483285841698.dkr.ecr.ca-central-1.amazonaws.com/circle-vijay:base
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY  # can specify string literal values
          aws_secret_access_key: $AWS_SECRET_KEY  # or project UI envar reference
jobs: 
  build:
    executor: default
    steps:
      - checkout
      - run: exit 1
      - run: 
          name: API call to report status (on success)
          command: |
             curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $VIJAY_GITHUB_PAT" https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/statuses/$CIRCLE_SHA1 -d '{"state":"success","target_url":"https://github.com/vjpandian/server4-pr-test","description":"Your tests passed on CircleCI Enterprise","context":"ci/circleci_enterprise:build"}'
          when: on_success
      - run: 
          name: API call to report status (on failure)
          command: |
             curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $VIJAY_GITHUB_PAT" https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/statuses/$CIRCLE_SHA1 -d '{"state":"failure","target_url":"https://github.com/vjpandian/server4-pr-test","description":"Your tests failed on CircleCI Enterprise","context":"ci/circleci_enterprise:build"}'
          when: on_fail

             

workflows:
  main:
    jobs:
      - build:
          context: org-global
