version: 2.1
executors:
  default:
    docker:
      - image: postgres:latest
jobs: 
  build:
    executor: default
    #machine: true
    #docker_layer_caching: true
    steps:
      - checkout
workflows:
  main:
    jobs:
      - build
